version: '3.8'

services:
  gamerecommender:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/game-recommender}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:2002
      - ConnectionStrings__DefaultConnection=Data Source=/data/gamerecommender.db
      - Steam__ApiKey=${STEAM_API_KEY}
    volumes:
      - gamerecommender_data:/data
    ports:
      - "2002:2002"
    restart: unless-stopped
    networks:
      - gamerecommender_net

volumes:
  gamerecommender_data:
    driver: local

networks:
  gamerecommender_net:
    driver: bridge 